module.exports = {
  "sethubble-guide": "SetHubble Guides",
  "sethubble-strategy": "SetHubble Strategies",
  "sethubble-partnership": "Partnership Program",
  "affiliate-marketing": "Affiliate Marketing",
  "referral-system": "Referral Systems",
  automation: "Business Automation",
  "growth-strategies": "Growth Hacking",
  traffic: "Traffic Generation",
  "passive-income": "Passive Income",
  cryptocurrencies: "Crypto & Web3",
  "crypto-payments": "Crypto Payments",
  monetization: "Monetization",
  "income-calculator": "Income Calculator",
  "binary-system": "Binary System",
  "linear-system": "Linear System",
  "digital-trap": "Digital Trap",
  "for-authors": "For Product Owners",
  "for-partners": "For Agents",
  "case-study": "Case Studies",
  news: "News & Updates",
  comparison: "Comparisons",
};
